spring:
  application:
    name: product-catalog-spring-boot

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/product_catalog
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  jpa:
    hibernate:
      ddl-auto: create


server:
  port: 8080

management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
    tags:
      application: ${spring.application.name}

otel:
  propagators:
    - tracecontext
  exporter:
    otlp:
      protocol: http/protobuf

